"""
Vector store builder for the annual report Q&A project.

Loads the pre-computed vectors from embed_chunks.py (embeddings.npy) together
with their text and metadata (chunk_metadata.json) into a persistent ChromaDB
collection, ready for similarity search in the query step.

Embeddings are inserted directly rather than recomputed, so this script can be
re-run cheaply (e.g. after changing metadata) without re-embedding the corpus.

Note: because vectors are supplied here rather than generated by Chroma, the
query step MUST encode its queries with the same model used in embed_chunks.py
(all-MiniLM-L6-v2 by default). Vectors from different models are not comparable.

Usage:
    python build_vectorstore.py --input_dir ./embeddings --db_dir ./chroma_db
"""

import argparse
import json
from pathlib import Path

import chromadb
import numpy as np

DEFAULT_COLLECTION = "annual_reports"


def load_embedding_artifacts(input_dir: Path) -> tuple[np.ndarray, list[dict]]:
    """
    Load the vector array and chunk metadata written by embed_chunks.py.

    Raises:
        FileNotFoundError: If either expected file is missing.
        ValueError: If the vector count and metadata count disagree, which
            would mean rows and chunks are misaligned.
    """
    vectors_path = input_dir / "embeddings.npy"
    metadata_path = input_dir / "chunk_metadata.json"

    if not vectors_path.exists():
        raise FileNotFoundError(f"Missing vectors: {vectors_path}")
    if not metadata_path.exists():
        raise FileNotFoundError(f"Missing metadata: {metadata_path}")

    vectors = np.load(vectors_path)
    chunks = json.loads(metadata_path.read_text(encoding="utf-8"))

    if len(vectors) != len(chunks):
        raise ValueError(
            f"Vector count ({len(vectors)}) does not match chunk count ({len(chunks)}). "
            "Re-run embed_chunks.py to regenerate both files together."
        )

    return vectors, chunks


def build_collection(
    vectors: np.ndarray,
    chunks: list[dict],
    db_dir: Path,
    collection_name: str = DEFAULT_COLLECTION,
    batch_size: int = 500,
) -> int:
    """
    Insert vectors, text and metadata into a persistent ChromaDB collection.

    Any existing collection with the same name is deleted first, so re-running
    this script produces a clean rebuild rather than duplicating entries.

    Each entry stores four things: the chunk_id, the vector, the chunk text
    (returned at query time and passed to the LLM), and the metadata fields
    used for filtered search (company, year, source_file, chunk_index).

    Args:
        vectors: 2D array of embeddings, one row per chunk.
        chunks: Chunk dicts in the same order as the vector rows.
        db_dir: Folder for ChromaDB's on-disk storage.
        collection_name: Name of the collection to create.
        batch_size: Entries inserted per add() call.

    Returns:
        The number of entries in the collection after loading.
    """
    db_dir.mkdir(parents=True, exist_ok=True)
    client = chromadb.PersistentClient(path=str(db_dir))

    # Rebuild from scratch so re-runs stay idempotent.
    try:
        client.delete_collection(collection_name)
        print(f"Removed existing collection '{collection_name}'")
    except Exception:
        pass

    collection = client.create_collection(collection_name)

    ids = [c["chunk_id"] for c in chunks]
    documents = [c["text"] for c in chunks]
    metadatas = [
        {
            "company": c["company"],
            # Chroma metadata values must be str/int/float/bool, never None.
            "year": c["year"] if c["year"] is not None else -1,
            "source_file": c["source_file"],
            "chunk_index": c["chunk_index"],
        }
        for c in chunks
    ]

    for start in range(0, len(ids), batch_size):
        end = start + batch_size
        collection.add(
            ids=ids[start:end],
            embeddings=vectors[start:end].tolist(),
            documents=documents[start:end],
            metadatas=metadatas[start:end],
        )
        print(f"  Inserted {min(end, len(ids))}/{len(ids)}")

    return collection.count()


def main():
    """Parse CLI arguments and build the vector store."""
    parser = argparse.ArgumentParser(description="Load embedded chunks into a ChromaDB collection.")
    parser.add_argument("--input_dir", type=str, default="./embeddings", help="Directory containing embeddings.npy and chunk_metadata.json")
    parser.add_argument("--db_dir", type=str, default="./chroma_db", help="Directory for the persistent ChromaDB store")
    parser.add_argument("--collection", type=str, default=DEFAULT_COLLECTION, help="Collection name")
    parser.add_argument("--batch_size", type=int, default=500, help="Entries inserted per add() call")
    args = parser.parse_args()

    input_dir = Path(args.input_dir)
    print(f"Loading embedding artifacts from {input_dir}...")
    vectors, chunks = load_embedding_artifacts(input_dir)
    print(f"Loaded {len(vectors)} vectors of dimension {vectors.shape[1]}")

    count = build_collection(vectors, chunks, Path(args.db_dir), args.collection, args.batch_size)

    companies = sorted({c["company"] for c in chunks})
    print(f"\nDone. Collection '{args.collection}' contains {count} entries.")
    print(f"Companies indexed: {', '.join(companies)}")
    print(f"Store persisted at {Path(args.db_dir).resolve()}")


if __name__ == "__main__":
    main()